name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Rust Version
        run: rustc --version

      - name: Check Cargo Version
        run: cargo --version

      - name: Build Project
        run: cargo build

      - name: Check Formatting
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

      - name: Run Tests
        run: cargo test