name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Cargo Dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Project
      run: cargo build

    - name: Check Formatting
      run: cargo fmt --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run Tests
      run: cargo test

    - name: Build Release Binary
      run: cargo build --release

    - name: Upload Release Binary
      uses: actions/upload-artifact@v4
      with:
      name: banking-api-rust
      path: target/release/banking-api-rust